blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/security/advisories/new
    about: Please report security vulnerabilities privately.
